matsumoto-group/matsumoto

README.md
app/views/layouts/application.html.erb

・Rubyのバージョンだけ追加
・テストとしてpushしました

[update]readme.md

---

.gitignore

Add[.gitignoreにに記述]

---

db/migrate/20190618092139_devise_create_customers.rb
db/migrate/20190618092155_devise_create_admins.rb
db/schema.rb

・customerのmigrationファイルのtrackableのコメントアウトを外した
・customer tableにカラム追加

[add] all columns to customer table

---

Gemfile
Gemfile.lock
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb

first commit

---

app/models/cart_album.rb
app/models/order_album.rb
db/migrate/20190619075625_create_cart_albums.rb
db/migrate/20190619080631_create_order_albums.rb
db/schema.rb
test/fixtures/cart_albums.yml
test/fixtures/order_albums.yml
test/models/cart_album_test.rb
test/models/order_album_test.rb

・CartAlbums とOrderAlbumsのModelを作成
・modelをmigrate済み

[Add] Model作成--01

---

app/models/album.rb
app/models/album_singer.rb
app/models/album_song.rb
app/models/disc.rb
app/models/order.rb
app/models/singer.rb
app/models/song.rb
db/migrate/20190619075715_create_songs.rb
db/migrate/20190619075902_create_singers.rb
db/migrate/20190619080158_create_album_songs.rb
db/migrate/20190619080244_create_album_singers.rb
db/migrate/20190619080328_create_discs.rb
db/migrate/20190619080557_create_albums.rb
db/migrate/20190619080825_create_orders.rb
db/schema.rb
test/fixtures/album_singers.yml
test/fixtures/album_songs.yml
test/fixtures/albums.yml
test/fixtures/discs.yml
test/fixtures/orders.yml
test/fixtures/singers.yml
test/fixtures/songs.yml
test/models/album_singer_test.rb
test/models/album_song_test.rb
test/models/album_test.rb
test/models/disc_test.rb
test/models/order_test.rb
test/models/singer_test.rb
test/models/song_test.rb

- モデルを作成
Album / AlbumSong / AlbumSinger / Order / Singe / Song / Disc
- 補足
・migrateは完了

[add] Model作成--02

---

app/assets/javascripts/costomers.coffee
app/assets/stylesheets/costomers.scss
app/controllers/costomers_controller.rb
app/helpers/costomers_helper.rb
test/controllers/costomers_controller_test.rb

[Add] controller 作成

---

config/routes.rb

[Add] Routing

---

app/models/album.rb
app/models/album_singer.rb
app/models/album_song.rb
app/models/cart_album.rb
app/models/customer.rb
app/models/disc.rb
app/models/order.rb
app/models/order_album.rb
app/models/singer.rb
app/models/song.rb
app/ubuntu-bionic-18.04-cloudimg-console.log

[update] アソシエーション 設定

---

app/controllers/albums_controller.rb
app/views/admins/confirmations/new.html.erb
app/views/admins/mailer/confirmation_instructions.html.erb
app/views/admins/mailer/email_changed.html.erb
app/views/admins/mailer/password_change.html.erb
app/views/admins/mailer/reset_password_instructions.html.erb
app/views/admins/mailer/unlock_instructions.html.erb
app/views/admins/passwords/edit.html.erb
app/views/admins/passwords/new.html.erb
app/views/admins/registrations/edit.html.erb
app/views/admins/registrations/new.html.erb
app/views/admins/sessions/new.html.erb
app/views/admins/shared/_error_messages.html.erb
app/views/admins/shared/_links.html.erb
app/views/admins/unlocks/new.html.erb
app/views/customers/confirmations/new.html.erb
app/views/customers/mailer/confirmation_instructions.html.erb
app/views/customers/mailer/email_changed.html.erb
app/views/customers/mailer/password_change.html.erb
app/views/customers/mailer/reset_password_instructions.html.erb
app/views/customers/mailer/unlock_instructions.html.erb
app/views/customers/passwords/edit.html.erb
app/views/customers/passwords/new.html.erb
app/views/customers/registrations/edit.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
app/views/customers/shared/_error_messages.html.erb
app/views/customers/shared/_links.html.erb
app/views/customers/unlocks/new.html.erb

[Add] devise views

---

app/assets/stylesheets/application.css
app/views/layouts/application.html.erb

[Add] header

---

app/assets/stylesheets/admins.scss
app/assets/stylesheets/application.css
app/assets/stylesheets/costomers.scss
app/controllers/admins/confirmations_controller.rb
app/controllers/admins/omniauth_callbacks_controller.rb
app/controllers/admins/passwords_controller.rb
app/controllers/admins/registrations_controller.rb
app/controllers/admins/sessions_controller.rb
app/controllers/admins/unlocks_controller.rb
app/controllers/admins_controller.rb
app/controllers/costomers_controller.rb
app/controllers/customers/confirmations_controller.rb
app/controllers/customers/omniauth_callbacks_controller.rb
app/controllers/customers/passwords_controller.rb
app/controllers/customers/registrations_controller.rb
app/controllers/customers/sessions_controller.rb
app/controllers/customers/unlocks_controller.rb
app/controllers/customers_controller.rb
app/views/admins/sessions/new.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
config/initializers/devise.rb
config/routes.rb

[add&update] 管理者ログイン画面 | deviseコントローラー作成 | 管理者画面のスタイル

---

app/assets/stylesheets/application.css

[update] application.css

---

app/controllers/albums_controller.rb
app/views/templates/album_all.html.erb

[add] templateフォルダ [update] albums_controller index new create

---

app/assets/javascripts/admins/contacts.coffee
app/assets/javascripts/admins/customers.coffee
app/assets/javascripts/admins/customers/orders.coffee
app/assets/stylesheets/admins/contacts.scss
app/assets/stylesheets/admins/customers.scss
app/assets/stylesheets/admins/customers/orders.scss
app/controllers/admins/albums_controller.rb
app/controllers/admins/base.rb
app/controllers/admins/contacts_controller.rb
app/controllers/admins/customers/orders_controller.rb
app/controllers/admins/customers_controller.rb
app/helpers/admins/contacts_helper.rb
app/helpers/admins/customers/orders_helper.rb
app/helpers/admins/customers_helper.rb
app/models/album.rb
app/views/admins/albums/new.html.erb
app/views/admins/contacts/index.html.erb
app/views/admins/contacts/show.html.erb
app/views/admins/customers/edit.html.erb
app/views/admins/customers/index.html.erb
app/views/admins/customers/orders/destroy.html.erb
app/views/admins/customers/show.html.erb
config/routes.rb
db/migrate/20190622063414_add_jacket_image_id_to_albums.rb
db/schema.rb
test/controllers/admins/contacts_controller_test.rb
test/controllers/admins/customers/orders_controller_test.rb
test/controllers/admins/customers_controller_test.rb
ubuntu-bionic-18.04-cloudimg-console.log

[Add] 商品追加画面

---

app/controllers/customers/registrations_controller.rb
app/views/customers/registrations/new.html.erb

[update] customer sign_upの機能、会員情報詳細画面の表示昨日実装

---

app/views/layouts/application.html.erb

[fix] jqueryの読み込み場所変更

---

Gemfile
Gemfile.lock
app/assets/javascripts/admins/admins.js
app/assets/javascripts/application.js
app/assets/stylesheets/albums.scss
app/controllers/admins/albums_controller.rb
app/controllers/albums_controller.rb
app/models/album.rb
app/models/album_singer.rb
app/models/album_song.rb
app/models/disc.rb
app/views/admins/albums/_album_infos.html.erb
app/views/admins/albums/_album_singers.html.erb
app/views/admins/albums/_album_songs.html.erb
app/views/admins/albums/_disc_fields.html.erb
app/views/admins/albums/_form.html.erb
app/views/admins/albums/_singer_fields.html.erb
app/views/admins/albums/_song_fields.html.erb
app/views/admins/albums/confirm.html.erb
app/views/admins/albums/edit.html.erb
app/views/admins/albums/index.html.erb
app/views/albums/index.html.erb
app/views/albums/show.html.erb
app/views/templates/_album_all.html.erb
db/schema.rb

[Add] 商品投稿　詳細

---

app/controllers/cart_albums_controller.rb
app/views/albums/show.html.erb
config/routes.rb

カート機能実装した。
・cart_albums　コントローラー作成
・ルーティング変更
・商品詳細のカートに追加するボタンを作成

[Add] カート機能

---

db/migrate/20190630094911_add_first_name_to_customers.rb

[Add] customer columns

---

app/assets/javascripts/order_albums.coffee
app/assets/stylesheets/order_albums.scss
app/controllers/customers/order_albums_controller.rb
app/controllers/customers/orders_controller.rb
app/controllers/customers_controller.rb
app/helpers/order_albums_helper.rb
app/models/customer.rb
app/models/order.rb
app/models/order_album.rb
app/views/templates/_customer_show_infos.html.erb
config/routes.rb
test/controllers/order_albums_controller_test.rb

購入履歴表示（album_nameだけデータ整える必要あり）

---

app/controllers/cart_albums_controller.rb
app/controllers/customers/orders_controller.rb
app/views/customers/_form.html.erb
app/views/templates/_customer_show_infos.html.erb
config/routes.rb
db/migrate/20190714115352_drop_table_cartalbums.rb

[done] カート内アルバム数量変更機能&画面

---

app/assets/stylesheets/customers.scss
app/controllers/customers/orders_controller.rb
app/views/templates/_customer_show_infos.html.erb
ubuntu-bionic-18.04-cloudimg-console.log

在庫数調整機能と購入履歴のレイアウトと表示データ

---

app/controllers/customers/orders_controller.rb

[update] order_albumの保存機能

---

app/controllers/customers/orders_controller.rb
app/views/admins/customers/edit.html.erb
app/views/admins/customers/show.html.erb
app/views/customers/_form.html.erb
app/views/templates/_customer_show_infos.html.erb

個数変更、配達ステータス改良

---

app/assets/stylesheets/albums.scss
app/assets/stylesheets/application.css
app/assets/stylesheets/customers.scss
app/controllers/admins/albums_controller.rb
app/controllers/admins/customers_controller.rb
app/controllers/application_controller.rb
app/views/admins/albums/_form.html.erb
app/views/admins/albums/new.html.erb
app/views/admins/albums/show.html.erb
app/views/admins/customers/show.html.erb
app/views/customers/show.html.erb
app/views/layouts/application.html.erb

[update] layouts

---

app/views/customers/registrations/new.html.erb

[add] 注意書き

---

app/views/customers/_form.html.erb
app/views/templates/_customer_show_infos.html.erb

[fix] last_name first_name

---

app/views/templates/_customer_show_infos.html.erb

Fix design mypage

---

app/controllers/customers/orders_controller.rb
app/views/customers/show.html.erb

Fix tax shipping cost

---

app/views/customers/show.html.erb
app/views/layouts/application.html.erb

[fix] turbolinks

---

app/controllers/customers/orders_controller.rb
app/views/admins/albums/_album_infos.html.erb
app/views/albums/show.html.erb

Fix stock_quantity button

---

app/assets/stylesheets/application.css
app/assets/stylesheets/customers.scss
app/assets/stylesheets/customers/customers.scss
app/models/order_album.rb
app/views/customers/orders/confirm.html.erb
app/views/customers/orders/new.html.erb
app/views/templates/_customer_show_infos.html.erb

[update] layout updated

---

app/assets/stylesheets/customers.scss
app/views/templates/_customer_show_infos.html.erb

[update] some layouts

---

README.md

[Fix] Readme
